### ISSUE TITLE
Feature request: replace variable names with labels

### ISSUE THREAD

**Issue by jzadra** [walkerke/tidycensus#142]
It would be great if there was an argument to replace variable names (B01001_001) with the label (Estimate!!Total).

**Comment by walkerke** [comment]
@jzadra While I agree with you, the problem is that many labels are duplicated across different variable groups/tables.  For example "Estimate!!Total" is found as a summary variable for many tables and would not be able to identify the specific variable, so I won't be able to implement this.  

A possible related alternative is to incorporate the new "tags" feature for version 1.0 (https://api.census.gov/data/2017/acs/acs5/tags.html) which allows users to pull related variables by intuitive label.  I'll be exploring this option sometime this month.
