### ISSUE TITLE
incorrect data returning using get_decennial sf3 2000

### ISSUE THREAD

**Issue by mjwebster** [walkerke/tidycensus#155]
I'm trying to get a few variables from the P021 table in sf3 2000 for counties in Minnesota. It's returning data for all 87 counties, but the values don't match what I get when I pull up that table in American FactFinder. For example, Becker county should have close to 4,000 total residents, but the results are coming up with something like 1,100.  

here's my code: 

placebirth2000 <-  get_decennial(geography= "county", state="MN", year=2000,dataset="sf3", variables=c(total= "P021001", native="P021002", foreignborn="P021013"), output="wide")

**Comment by mfherman** [comment]
Hi @mjwebster. The issue here is that `get_decennial()` uses an argument called `sumfile` and not `dataset` to specify which summary file to use. So in your code above, the function doesn't see `sumfile` specified and defaults to using SF1, instead of SF3. So your code is actually pulling from [SF1 table P021](https://www.socialexplorer.com/data/C2000/metadata/?ds=SF1&table=P021). 

See below output from SF3 table P021, which appears to match results from American FactFinder:

``` r
library(tidycensus)

get_decennial(
  geography= "county",
  state = "MN",
  year = 2000,
  sumfile = "sf3",
  variables = c(
    total = "P021001",
    native ="P021002",
    foreignborn = "P021013"
    ),
  output = "wide"
  )
#> Getting data from the 2000 decennial Census
#> # A tibble: 87 x 5
#>    GEOID NAME               total native foreignborn
#>    <chr> <chr>              <dbl>  <dbl>       <dbl>
#>  1 27001 Aitkin County      15301  15158         143
#>  2 27003 Anoka County      298084 287313       10771
#>  3 27005 Becker County      30000  29691         309
#>  4 27007 Beltrami County    39650  38937         713
#>  5 27009 Benton County      34226  33494         732
#>  6 27011 Big Stone County    5820   5774          46
#>  7 27013 Blue Earth County  55941  54313        1628
#>  8 27015 Brown County       26911  26572         339
#>  9 27017 Carlton County     31671  31172         499
#> 10 27019 Carver County      70205  67806        2399
#> # ... with 77 more rows
```

<sup>Created on 2019-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mjwebster** [comment]
Ahhh! Thank you! Does the same work for 1990 data? Because I used dataset to pull and got the right stuff.

**Comment by mfherman** [comment]
Hmm, you might want to double check that you got the data you were expecting. No matter the year, you should use the `sumfile` argument instead of `dataset`. See an example below from 1990 that pulls different data depending on if you use `dataset` instead of `sumfile`. To be clear, they are both "correct" data, it is just that when using the `dataset` argument, `get_decennial()` ignores it and choose the default summary file, SF1, to pull from.

``` r
library(tidycensus)

get_decennial(
  geography= "county",
  state = "MN",
  year = 1990,
  sumfile = "sf3",
  variables = "P0060003",
  output = "wide"
)
#> Getting data from the 1990 decennial Census
#> # A tibble: 87 x 3
#>    GEOID NAME              P0060003
#>    <chr> <chr>                <dbl>
#>  1 27001 Aitkin County          828
#>  2 27003 Anoka County           694
#>  3 27005 Becker County         2427
#>  4 27007 Beltrami County       1145
#>  5 27009 Benton County         2595
#>  6 27011 Big Stone County      1127
#>  7 27013 Blue Earth County     3674
#>  8 27015 Brown County          3585
#>  9 27017 Carlton County         817
#> 10 27019 Carver County         3056
#> # … with 77 more rows

get_decennial(
  geography= "county",
  state = "MN",
  year = 1990,
  dataset = "sf3",
  variables = "P0060003",
  output = "wide"
)
#> Getting data from the 1990 decennial Census
#> # A tibble: 87 x 3
#>    GEOID NAME              P0060003
#>    <chr> <chr>                <dbl>
#>  1 27001 Aitkin County          175
#>  2 27003 Anoka County          1865
#>  3 27005 Becker County         1861
#>  4 27007 Beltrami County       5641
#>  5 27009 Benton County          123
#>  6 27011 Big Stone County        26
#>  7 27013 Blue Earth County      132
#>  8 27015 Brown County            15
#>  9 27017 Carlton County        1297
#> 10 27019 Carver County          112
#> # … with 77 more rows
```

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mjwebster** [comment]
@mfherman Yes that turned out to be the problem. Using "sumfile" I got exactly what I expected to get. I think this issue can be closed, but I'm not sure if that's something I'm able to do?  Thanks everyone.
