### ISSUE TITLE
acs1 missing values 

### ISSUE THREAD

**Issue by przemo** [walkerke/tidycensus#157]
Hi, 
I am using the code that used to work before, but when I rerun it there are no estimates returned - everything is missing. Is it a problem with Census API or some updated feature I should use?

```r
x <- get_acs(geography = "state", variables = "DP03_0119",
        geometry = F, year = 2015, survey = "acs1")
x
```

```r
# A tibble: 52 x 5
   GEOID NAME                 variable  estimate   moe
   <chr> <chr>                <chr>        <dbl> <dbl>
 1 01    Alabama              DP03_0119       NA    NA
 2 02    Alaska               DP03_0119       NA    NA
 3 04    Arizona              DP03_0119       NA    NA
```

No errors are returned.

**Comment by mfherman** [comment]
I'm not sure when this changed, but if you take a look at DP03 through American Fact Finder, you'll see estimates for DP03_0119 are not available.

![Screen Shot 2019-04-17 at 21 04 17](https://user-images.githubusercontent.com/24945757/56330044-67e94a00-6154-11e9-9ab5-60347ce34af4.png)

Similarly, if you try to access this variable via the API, you get all `-888888888`. 

https://api.census.gov/data/2017/acs/acs1/profile?get=DP03_0119E,NAME&for=state:*

So in this case, `tidycensus` returns `NA` because it gets  `-888888888` from the Census API. 

You could pull this same data from subject or detail tables which are also accessible through `tidycensus`. Take a look at tables S1702 and/or B17010 and see if they have what you need.

**Comment by przemo** [comment]
Thanks for looking into this!
PJ
