### ISSUE TITLE
get_estimates for components not pulling recent years. 

### ISSUE THREAD

**Issue by CVIOG-Demography** [walkerke/tidycensus#169]
get_estimates for components not pulling recent years. I contacted the Census Bureau and said it would be something in the package needing updating. 

get_estimates(geography = "state",
                               state = "Georgia",
                               product = "components", 
                               time_series = TRUE,
                               geometry = TRUE, 
                               year = 2017)

Only fetches through PERIOD 8, 2015 (call specifies through PERIOD 10 or year 2017)

> table(ga_components$PERIOD)
 1  2  3  4  5  6  7  8 
12 12 12 12 12 12 12 12 

R 3.6.0
tidycensus 0.9

**Comment by mfherman** [comment]
For 2017, the PERIOD would only go up to 8 (July 1, 2016 to June 30, 2017). But, for other products that are reported by DATE instead of by Period, they go up to 10 (July 1, 2017 population or housing unit estimate). See the detailed period and date ranges here: https://www.census.gov/data/developers/data-sets/popest-popproj/popest/popest-vars/2017.html

For example, if you pull the `housing` product, you'll see values of DATE from 1 to 10. 

``` r
library(tidycensus)

get_estimates(geography = "state",
              state = "Georgia",
              product = "housing",
              time_series = TRUE,
              geometry = FALSE,
              year = 2017)
#> # A tibble: 10 x 5
#>    NAME     DATE GEOID variable   value
#>    <chr>   <dbl> <chr> <chr>      <dbl>
#>  1 Georgia     1 13    HUEST    4088801
#>  2 Georgia     2 13    HUEST    4088884
#>  3 Georgia     3 13    HUEST    4091963
#>  4 Georgia     4 13    HUEST    4103452
#>  5 Georgia     5 13    HUEST    4116164
#>  6 Georgia     6 13    HUEST    4134411
#>  7 Georgia     7 13    HUEST    4164303
#>  8 Georgia     8 13    HUEST    4197251
#>  9 Georgia     9 13    HUEST    4236284
#> 10 Georgia    10 13    HUEST    4282106
```

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by walkerke** [comment]
@mfherman is correct.  As a notable aside - by setting `year` to 2018 you can get the most recent data now as I just pushed a fix due to a change in the API.
