### ISSUE TITLE
Request: Census designated place by county?

### ISSUE THREAD

**Issue by emorrow3** [walkerke/tidycensus#177]
Any chance we could get the ability to query places(cities/towns) by County? 

Or any thoughts for a work around...for example: only the towns in Taliaferro County, GA, as opposed to all in the state of GA? 

I'm somewhat new to this, so my apologies if it's a silly question.

Thanks!

**Comment by mfherman** [comment]
Not a silly question at all, @emorrow3. Unfortunately it isn't possible to request via the 
Census API because some census places cross county boundaries. You can see which geographies are available by county here:

https://walkerke.github.io/tidycensus/articles/basic-usage.html#geography-in-tidycensus

But, this brings up a fun workaround which involves getting place and county geometries from the [`tigris` package](https://github.com/walkerke/tigris) and performing a [spatial join with the `sf` package](https://r-spatial.github.io/sf/reference/st_join.html) to identify which counties intersect each place in Georgia. From there, we can filter to only get the places that intersect with Taliaferro County and use the GEOIDs of those places to filter the set of all places in Georgia that is returned from `get_acs()`.

Note: I set `largest = TRUE` in `st_join()` so that I only get one county per place. In this case, it will be the county with the largest overlap. If you are ok with place falling into more than one county, you could make this to `FALSE`.

``` r
library(tidycensus)
library(tidyverse)
library(tigris)
library(sf)

# get place and county geometries from {tigris}
ga_places <- tigris::places(state = "GA", cb = TRUE, class = "sf") %>% 
  select(place_fips = GEOID, place_name = NAME)

ga_counties <- tigris::counties(state = "GA", cb = TRUE, class = "sf") %>% 
  select(county_fips = GEOID, county_name = NAME)

# spatial join places and counties to get counties that intersect places
# only select the county that has the largest overlap with each place
taliaferro_places <- st_join(ga_places, ga_counties, largest = TRUE) %>% 
  filter(county_name == "Taliaferro")

# get acs data for all places in ga
ga_places_acs <- get_acs(
  geography = "place",
  variables = "B01003_001",
  state = "GA",
  year = 2017
  )
#> Getting data from the 2013-2017 5-year ACS

# filter for only places within taliaferro county
ga_places_acs %>% 
  filter(GEOID %in% taliaferro_places$place_fips)
#> # A tibble: 2 x 5
#>   GEOID   NAME                        variable   estimate   moe
#>   <chr>   <chr>                       <chr>         <dbl> <dbl>
#> 1 1320316 Crawfordville city, Georgia B01003_001      709   133
#> 2 1369896 Sharon city, Georgia        B01003_001      138    39

# make a little map
ggplot(taliaferro_places) +
  geom_sf(data = filter(ga_counties, county_name == "Taliaferro")) +
  geom_sf(color = "blue") +
  ggsflabel::geom_sf_text_repel(aes(label = place_name), nudge_x = 0.03, nudge_y = -0.02) +
  labs(title = "Census places in Taliaferro County, GA") +
  theme_void()
```

![](https://i.imgur.com/jXgYuW1.png)

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by walkerke** [comment]
Thanks for the detailed example, @mfherman!

This is functionality that would be cool to have in tidycensus and I believe they've implemented something like it over on the Python side in [cenpy](https://github.com/cenpy-devs/cenpy).  I'd need to fully support geometry for all geographies in tidycensus and then include internal overlay logic, which is do-able but it'd be a fair amount of work.

**Comment by walkerke** [comment]
Closing this as I'm going to stick with @mfherman's workflow to avoid assumptions around spatial predicate issues.  I've also got some examples in the upcoming book for how to do this as I think it makes sense for analysts to do this explicitly with `st_filter()`.
