### ISSUE TITLE
get_decennial not working for 2000 and 2010

### ISSUE THREAD

**Issue by thelittlerock** [walkerke/tidycensus#197]
I am unable to get decennial data for the years 2000 and 2010:

`> get_decennial(geography="state", state="California", year = 2000, table = "P12")`
`Getting data from the 2000 decennial Census`

`> get_decennial(geography="state", state="California", year = 2010, table = "P12")`
`Getting data from the 2010 decennial Census`
`Error in open.connection(x, "rb") : HTTP error 404.`

**Comment by mfherman** [comment]
I can confirm this bug -- it seems like it's actually happening when trying to load the lookup table to choose which variables belong to table P12. I'll dig a little more to see if this is a Census API issue or a tidycensus bug.

``` r
library(tidycensus)
load_variables(year = 2010, dataset = "sf3")
#> Error in open.connection(x, "rb"): HTTP error 404.
```

<sup>Created on 2019-11-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mfherman** [comment]
Now I see what's going on -- you need table `P012` not `P12`. See below for working example. 

And then on the error from `load_variables()`, Summary File 3 was not published in 2010 because those detailed tables were moved to the American Community Survey, so the attempted call the Census API errors out. In #203, I added in a brief check to error if `sf3` is requested for 2010. Incidentally, the reason you see the same error message running `load_variables(year = 2010, dataset = "sf3")` and `get_decennial()` is that `P12` is not found in `sf1`, so it goes looking in `sf3` for that table.

``` r
library(tidycensus)

get_decennial(
  geography = "state",
  state = "California",
  year = 2000,
  table = "P012"
  )
#> Getting data from the 2000 decennial Census
#> # A tibble: 49 x 4
#>    GEOID NAME       variable    value
#>    <chr> <chr>      <chr>       <dbl>
#>  1 06    California P012001  33871648
#>  2 06    California P012002  16874892
#>  3 06    California P012003   1272884
#>  4 06    California P012004   1396480
#>  5 06    California P012005   1317135
#>  6 06    California P012006    758039
#>  7 06    California P012007    513587
#>  8 06    California P012008    258628
#>  9 06    California P012009    247456
#> 10 06    California P012010    739446
#> # … with 39 more rows

get_decennial(
  geography = "state",
  state = "California",
  year = 2000,
  table = "P012"
)
#> Getting data from the 2000 decennial Census
#> # A tibble: 49 x 4
#>    GEOID NAME       variable    value
#>    <chr> <chr>      <chr>       <dbl>
#>  1 06    California P012001  33871648
#>  2 06    California P012002  16874892
#>  3 06    California P012003   1272884
#>  4 06    California P012004   1396480
#>  5 06    California P012005   1317135
#>  6 06    California P012006    758039
#>  7 06    California P012007    513587
#>  8 06    California P012008    258628
#>  9 06    California P012009    247456
#> 10 06    California P012010    739446
#> # … with 39 more rows
```

<sup>Created on 2019-11-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
