### ISSUE TITLE
Documentation around `table` arg in `get_acs()` 

### ISSUE THREAD

**Issue by JosiahParry** [walkerke/tidycensus#198]
Hey! First off, lovely package. I rely largely on this package for data discovery in the ACS. 

I believe that the `table` argument in `get_acs()` can be used as a way to pull all variables for an ACS call. Current documentation reads

> The ACS table for which you would like to request all variables. Uses lookup tables to identify the variables; performs faster when variable table already exists through load_variables(cache = TRUE).

Does this mean I can write `"acs5"` or `"acs1/subject"`? The point referencing `load_variables()` suggests setting the argument to a data frame which is created from `load_variables()`. 

Direction is greatly appreciated!

Edit: accidental markdown formatting

----
The below code follows the latter approach inferred. However returns only the first variable in the table.

```r
acs_vars <- tidycensus::load_variables(2017, "acs1/subject")

all_acs <- get_acs(geography = "tracts",
                   survey = "acs1/subject", 
                   year = 2017, 
                   table = acs_vars)
```

The function call returns the warnings:

```
In addition: Warning messages:
1: In if (grepl("^S[0-9].", table)) { :
  the condition has length > 1 and only the first element will be used
2: In if (grepl("^DP[0-9].", table)) { :
  the condition has length > 1 and only the first element will be used
3: In grepl(specific, df$name) :
  argument 'pattern' has length > 1 and only the first element will be used
```

**Comment by mfherman** [comment]
The table argument allows use to specify one table to get all variables from, not all subject tables from the ACS. (Perhaps we should include some error checking in get_acs() to only allow for one value to be passed to the table argument). An example of this usage is the following where we will get all variables from table B01001, instead of having to specify each of the variables in the table (e.g. B01001_001, B01001_003, B01001_003, etc.)

``` r
library(tidycensus)
get_acs(
  geography = "county",
  state = "VT",
  survey = "acs1",
  year = 2017,
  table = "B01001",
  cache_table = TRUE
)
#> Getting data from the 2017 1-year ACS
#> The one-year ACS provides data for geographies with populations of 65,000 and greater.
#> Loading ACS1 variables for 2017 from table B01001 and caching the dataset for faster future access.
#> # A tibble: 49 x 5
#>    GEOID NAME                       variable   estimate   moe
#>    <chr> <chr>                      <chr>         <dbl> <dbl>
#>  1 50007 Chittenden County, Vermont B01001_001   162372    NA
#>  2 50007 Chittenden County, Vermont B01001_002    79659   907
#>  3 50007 Chittenden County, Vermont B01001_003     4344   363
#>  4 50007 Chittenden County, Vermont B01001_004     4254  1076
#>  5 50007 Chittenden County, Vermont B01001_005     4047   978
#>  6 50007 Chittenden County, Vermont B01001_006     2500   186
#>  7 50007 Chittenden County, Vermont B01001_007     3465   139
#>  8 50007 Chittenden County, Vermont B01001_008     1208   497
#>  9 50007 Chittenden County, Vermont B01001_009     2868  1094
#> 10 50007 Chittenden County, Vermont B01001_010     5271  1098
#> # … with 39 more rows
```

<sup>Created on 2019-11-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The reference to `load_variables(cache = TRUE)` suggests that if at any point in the past, you have run say, `load_variables(2017, "acs1/subject", cache = TRUE)`, the variable lookup tables will be cached locally, and so when you run `get_acs()` and specify a table, it will use that cached copy of the lookup table, rather than querying the API to do the lookup and then send another API call to download the data for the appropriate variables. 

Another option is to set `cache_table = TRUE` in `get_acs()`, which will do the same caching. If you want to download ALL variables from the ACS, I would suggest you use [IPUMS](https://usa.ipums.org/usa/) or [censusapi](https://hrecht.github.io/censusapi/) instead of tidycensus.

**Comment by JosiahParry** [comment]
This is exceptionally helpful. Thank you!
