### ISSUE TITLE
Error in 2000 get_decennial() when geography is tract

### ISSUE THREAD

**Issue by kastanis** [walkerke/tidycensus#26]
`st <- c(datasets::state.abb, "DC")`
`population_2000 <- get_decennial(geography = "tract", endyear = 2000, variables = "P001001", state = st)`

Results in:

`Using FIPS code '01' for state 'AL'
Error : lexical error: invalid char in json text.
                                       <html><head><title>Apache Tomca
                     (right here) ------^

Error in gather.default(., key = variable, value = value, -GEOID, -NAME) : 
  object 'NAME' not found`

When I try it with 2010 data, it works (note, the variable is different):
`population_2010 <- get_decennial(geography = "tract", endyear = 2010, variables = "P0010001", state = st)`

**Comment by walkerke** [comment]
I'll take a look at this!

**Comment by keberwein** [comment]
@kastanis it works if you use `year=2000` instead of `endyear==2000`. The `get_acs()` function uses the `endyear` argument, while the get_decennial() function uses the `year` argument.

```
st <- c(datasets::state.abb, "DC")
population_2000 <- get_decennial(geography = "tract", year = 2000, variables = "P001001", state = st)
```

@walkerke I didn't make any changes but might want to think about changing one of these two function arguments, so they are the same. Otherwise, I'm sure this issue will come up again.

**Comment by walkerke** [comment]
Thanks @keberwein for answering this.  I'll look to update so that both `get_acs()` and `get_decennial()` accept either `year` or `endyear` as equivalent to avoid confusion.
