### ISSUE TITLE
Returning "NA" for some variables

### ISSUE THREAD

**Issue by aavafarhadi** [walkerke/tidycensus#271]
I am pulling out variables using tidycensus, but for some I just get "NA"--and I know there should be some values in them.
They are:

S1251_C01_010E - # child under 18 
S2602_C01_070E - not US citizen 
S2602_C01_081E - unemployment rate
S2602_C01_023E - quartile Black + Hispanic

Wondering if anyone has had issues with these variables as well? Also wondering how to mutate variables here. For example, I am looking at the # of people over 65, but I want that as a percent, so how would I create that to include it in my table? Thanks!!

**Comment by walkerke** [comment]
Could you include a reproducible example?  You might also consider using the `show_call = TRUE` argument and pasting the raw API call into your web browser.  This can often help with debugging.  Unfortunately not all variables are available at all geographies, and there isn't a central mapping of variables to available geographies, so this can require some trial and error.  

For those specific variables - consider taking a look at the ACS Data Profile instead, you may get where you need faster and it includes pre-calculated percentages for many variables.

**Comment by aavafarhadi** [comment]
` df <- get_acs(year = 2018, 
                variables = c(blackHis= "S2602_C01_023",
                              unEmployRate = "S2602_C01_081",
                              over_65 = "S0101_C01_030", 
                              below_pov = "S1603_C01_009",
                              HH_under_18 = "S1251_C01_010",
                              medhhi = "S2503_C01_013"),
                geography = "tract",
                state = st )
`
This is where the issue is! Also, I am new to r but I believe this is what you meant by reproducible example?

**Comment by walkerke** [comment]
Correct, some of those variables are not available at the Census tract level.  When I do: 

```r
library(tidycensus)
df <- get_acs(year = 2018, 
              variables = c(
                blackHis= "S2602_C01_023", 
                unEmployRate = "S2602_C01_081", 
                over_65 = "S0101_C01_030", 
                below_pov = "S1603_C01_009", 
                HH_under_18 = "S1251_C01_010", 
                medhhi = "S2503_C01_013"), 
              geography = "tract", 
              state = "HI")
```

I get: 

```
> df
# A tibble: 2,106 x 5
   GEOID     NAME                           variable   estimate   moe
   <chr>     <chr>                          <chr>         <dbl> <dbl>
 1 15001020… Census Tract 201, Hawaii Coun… over_65        1102   171
 2 15001020… Census Tract 201, Hawaii Coun… HH_under_…       NA    NA
 3 15001020… Census Tract 201, Hawaii Coun… below_pov      3932   337
 4 15001020… Census Tract 201, Hawaii Coun… medhhi        52719  9226
 5 15001020… Census Tract 201, Hawaii Coun… blackHis         NA    NA
 6 15001020… Census Tract 201, Hawaii Coun… unEmployR…       NA    NA
 7 15001020… Census Tract 202.02, Hawaii C… over_65         416    69
 8 15001020… Census Tract 202.02, Hawaii C… HH_under_…       NA    NA
 9 15001020… Census Tract 202.02, Hawaii C… below_pov      1785   226
10 15001020… Census Tract 202.02, Hawaii C… medhhi        46213  7892
# … with 2,096 more rows
```
This is because you are pulling from tables that are already themselves subsets (in the Subject Tables); I'd recommend looking at Data Profile variables (`load_variables(2018, "acs5/profile"`) or the regular ACS itself.  For example, Subject Table 2602 (which is giving you NAs) only corresponds to the group quarters population (college dorms, prisons, nursing homes, etc.) and does not reflect the total population.  So you'd want to look elsewhere for your data anyway most likely unless the GQ population is indeed your focus.  

Finding the right variables among the 1000s of ACS variables can admittedly be a challenge.  If `load_variables()` doesn't get you where you need to go, I like browsing the interactive interface provided by Census Reporter (https://censusreporter.org/).
