### ISSUE TITLE
5-year ACS ZCTA returns GEOID in different formats for 2019 vs prior years

### ISSUE THREAD

**Issue by laytonj-lsc** [walkerke/tidycensus#338]
Hi, just noting that for zip code tabulation areas the get_acs function returns a GEOID like "0135004" (with the "01" being the state) whereas prior years have returned "35004". The new format could make filtering by state easier, though I'm not so sure zip codes align with state boundaries. Either way, though, I just wanted to point this out in case the change was unintentional or, alternatively, so that it might be noted in the documentation for people like me who might have their code thrown off by the change. Thanks!

**Comment by walkerke** [comment]
@laytonj-lsc thank you so much!  this is a great catch.  You are correct that we'll need to fix this as `geometry = TRUE` is failing for 2019 ZCTAs as well due to this change.  Fingers crossed, this means that we'll be able to request ZCTAs by state from the API, which you correctly note that we haven't been able to do in prior years.  I'll investigate today!

**Comment by walkerke** [comment]
all fixed!  I'm excited that Census is allowing this option.  I'll send up to CRAN shortly.

**Comment by laytonj-lsc** [comment]
Awesome. Thank you so much for all your work on this.
