### ISSUE TITLE
2005 PEP

### ISSUE THREAD

**Issue by maryweber** [walkerke/tidycensus#342]
Is there a way to call this API through tidycensus? I'm trying to retrieve PEP data for 2005. I have an excel sheet of it, but would like to automate the process. 

https://api.census.gov/data/2000/pep/int_charagegroups.html

Thank you!

**Comment by mfherman** [comment]
The earliest PEP data we have available right now is from 2015 (although you can go back to 2010 if you request the time series data). One approach would be to use the [censusapi](https://cran.r-project.org/web/packages/censusapi/vignettes/getting-started.html) or construct the API call yourself and use [httr](https://cran.r-project.org/web/packages/httr/vignettes/quickstart.html) or another client to download the data from the API into R.

**Comment by walkerke** [comment]
I second @mfherman's suggestion to check out censusapi.  One of the brilliant things about that package is that you can access any of the APIs with highly customizable queries.  Older versions of PEP on the API are formatted differently from the years supported by tidycensus which is why we don't go back that far, and it isn't a top development priority at the moment.  However, PRs are always welcome!
