### ISSUE TITLE
x cannot coerce type 'closure' to vector of type 'character'

### ISSUE THREAD

**Issue by teyindawind** [walkerke/tidycensus#348]
This is what I'm using:
library(devtools)
library(tidyverse)
library(tidycensus)

meps_fullyear_2013<-
  readr::read_csv("ECON/MEPS_fullyear_2013.csv")

gg<-
  meps_2013%>%
  filter(totexp13>0)%>%
  as_tibble()%>%
  ggplot(aes(weight=perwt13f))+
  geom_histogram(aes(x=totexp13), bins=50, stat="bin")+
  xlab("Total spending")
GGally::ggmatrix(list(gg,gg+scale_x_log10()),1,2,c("Total spending", "Log of Total spending"))

meps_2013%>%
  filter(age31x %in% 60:68 & age31x!=64)%>%
  mutate(over=age31x>=65)%>%
  group_by(over)%>%
  summarize(across(as.character(vars),~weighted.mean(.,perwt13f)))%>%
  pivot_longer(-over,names_to="service")%>%
  pivot_wider(names_from=over,values_from=value)%>%
  inner_join(
    axis_names%>%enframe()%>%unnest(value),
    by=c("service"="name")
  )%>%
  select(value,`FALSE`,`TRUE`)

and I get the error:

Error: Problem with `summarise()` input `..1`.
x cannot coerce type 'closure' to vector of type 'character'
i Input `..1` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.
i The error occurred in group 1: over = FALSE.

**Comment by walkerke** [comment]
Hi @teyindawind!  I notice this is the first issue you've filed.  A few pieces of advice: 

1. You've filed this issue in the tidycensus repository but your code doesn't have anything to do with tidycensus.  We can only address issues concerning the package here.  
2. Generally, GitHub issues are used for specific bugs/problems in the package that the developers can address.  Yours appears to be a programming error, which GitHub issues aren't used to correct.  If you need programming help, I'd recommend posting to StackOverflow.  
3. When doing so, [be sure to produce a completely reproducible example](https://www.tidyverse.org/help/).  As your code requires reading in a dataset that is not provided, your code cannot be run by someone else.  

That said - I believe your problem is when you are calling `as.character(vars)`, as `vars()` is a function in dplyr and you can't coerce a function (a "closure") to a character, which your code is trying to do.

**Comment by szimmer** [comment]
I agree with what Kyle said except aging that in addition to stack overflow, community.rstudio.com may be a better venue for your question. Be sure to post a reproducible example keeping in mind we don't have access to that csv file.
