### ISSUE TITLE
PUMS Data Prior to 2017

### ISSUE THREAD

**Issue by mdonova** [walkerke/tidycensus#393]
Hi! I'm working on a project that requires comparing PUMS data between 2000 and 2019 but I noticed tidycensus only goes back to 2017. Is there a way to load PUMS data from 2000 using tidycensus?

**Comment by walkerke** [comment]
Thanks for your note!  tidycensus goes back to 2006 for the 1-year ACS PUMS and 2005-2009 for the 5-year ACS PUMS.  Variable recodes are only available back to 2017, which is why `pums_variables` only has a data dictionary since 2017.  Unfortunately, tidycensus only covers the ACS PUMS.  You'll want to use [IPUMS](https://usa.ipums.org/usa/) for your purposes, which has a companion R package [ipumsr](http://tech.popdata.org/ipumsr/).

**Comment by mdonova** [comment]
Thank you so much!
