### ISSUE TITLE
Unable to pull ZCTA boundaries using get_acs function

### ISSUE THREAD

**Issue by parnelli32** [walkerke/tidycensus#395]
Hi, I am trying to pull the zip code boundaries for Texas.  However, when I try and do so, I receive the error message "ZCTAs can only be requested for the entire country, not within states or counties."  I looked up this error message and it doesnt look like anyone else has encountered this yet, so I was hoping for some guidance.  Thanks!

**Comment by walkerke** [comment]
Thanks for filing - yes this is a bug that is carried through from the tigris package.  Recently Census made it possible to get ZCTA data from the ACS by state, but this is not possible right now in tidycensus when `geometry = TRUE` because the underlying `zctas()` function in tigris doesn't accept a state argument for ACS years.  Should be a quick fix.

**Comment by walkerke** [comment]
Re-install from GitHub and try now, it should work!

```r
library(tidycensus)

tx_zcta_pop <- get_acs(
  geography = "zcta",
  variables = "B01001_001",
  state = "TX",
  year = 2019,
  geometry = TRUE
)

plot(tx_zcta_pop['estimate'])
```

![image](https://user-images.githubusercontent.com/4872833/129474478-3c271240-12f9-4d23-8575-ebae3196293d.png)
