### ISSUE TITLE
2020 Census Data?

### ISSUE THREAD

**Issue by vinhdizzo** [walkerke/tidycensus#400]
Hi,

Are there plans to incorporate the 2020 data into the `tidycensus` package?  Thank you!

**Comment by walkerke** [comment]
2020 redistricting data _should_ be released to the API on September 16, and we'll support it ASAP afterward.  The regular 2020 Demographic and Housing Characteristics files (which is what we typically think of with respect to decennial Census data) do not have a published release date, so that is firmly TBD.  That said, we can look forward to 2016-2020 ACS data in December.

**Comment by vinhdizzo** [comment]
Thank you!
