### ISSUE TITLE
Similar entries in load_variables

### ISSUE THREAD

**Issue by bramtayl** [walkerke/tidycensus#402]
I've really enjoyed using this package so far. I'm running up against an annoying problem which might be an issue here or with the data:

There are seemingly duplicate entries in `load_variables`. For example,

```{r}
library(dplyr)
library(tidycensus)

load_variables(2000, "sf1", cache = TRUE) %>%
  filter(
    label == "Total" &
    concept == "SEX BY AGE [49]"
  )
```

will give two rows: "P012001" and "PCT013001". Are they supposed to have identical labels and concepts? If so, is there another way to distinguish them? Or is the census bureau playing tricks on me?

**Comment by walkerke** [comment]
Yeah, this is due to the way the information is specified in https://api.census.gov/data/2000/dec/sf1/variables.html, which does not distinguish between the two.  The first variable `P012001` reflects the total population, and the second variable `PCT013001` only reflects populations in households, so it excludes populations in group quarters.  You can get a bit more info here: https://www.census.gov/prod/cen2000/doc/sf1.pdf
