### ISSUE TITLE
NEWS.md not updated for latest 1.1.2 release

### ISSUE THREAD

**Issue by engineerchange** [walkerke/tidycensus#437]
Hello,

Great package! Saw the dasymetric update is up-and-coming via twitter, and I'm excited to play around with it. I wanted to note that the latest 1.1.2 release doesn't seem to have NEWS.md updated and I'm unable to parse https://github.com/walkerke/tidycensus/releases to see what has changed since 1.1.

**Comment by walkerke** [comment]
It was a very minor patch release (no new features) which is why I didn't update the log; you'll want to keep an eye on https://walker-data.com/tidycensus/news/index.html.  1.2 will have a bunch of new features including a 2020 default year for `get_acs()`, the `as_dot_density()` function for dot-density mapping, and probably support for the new population estimates data.
