### ISSUE TITLE
Meaning of "tidy" option in 'output' argument

### ISSUE THREAD

**Issue by pat-s** [walkerke/tidycensus#44]
Hi there,

according to https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html and my understanding of "tidy" data, variables should always be in their own column. 

When downloading data with `tidycensus` , the "tidy" option in the `output` argument puts all dowloaded variables in one column which is exactly the non-tidy version.

I guess that `output = wide` would reflect the "tidy" idea of the `tidyverse`. 
Especially because the package name is leaned on the `tidyverse`, I think that a change of the name argument name would be appropriate? :)

Thanks for the package, it really simplifies a lot :+1:

**Comment by walkerke** [comment]
Thanks for your note, I'm glad you find the package useful!

I am interpreting tidy data differently than your interpretation - this is a good opportunity to explain my design philosophy.   A good corollary here is taken from the link you provided - the "Column headers are values, not variable names" section with the income/religion example.  In this example, each religion is a row in the messy dataset, with income categories spread across the columns: 

```r
pew <- tbl_df(read.csv("pew.csv", stringsAsFactors = FALSE, check.names = FALSE))
pew
#> # A tibble: 18 x 11
#>    religi… `<$10… `$10-… `$20-… `$30… `$40… `$50… `$75… `$10… `>15… `Don'…
#>    <chr>    <int>  <int>  <int> <int> <int> <int> <int> <int> <int>  <int>
#>  1 Agnost…     27     34     60    81    76   137   122   109    84     96
#>  2 Atheist     12     27     37    52    35    70    73    59    74     76
#>  3 Buddhi…     27     21     30    34    33    58    62    39    53     54
#>  4 Cathol…    418    617    732   670   638  1116   949   792   633   1489
#>  5 Don’t …     15     14     15    11    10    35    21    17    18    116
#>  6 Evange…    575    869   1064   982   881  1486   949   723   414   1529
#>  7 Hindu        1      9      7     9    11    34    47    48    54     37
#>  8 Histor…    228    244    236   238   197   223   131    81    78    339
#>  9 Jehova…     20     27     24    24    21    30    15    11     6     37
#> 10 Jewish      19     19     25    25    30    95    69    87   151    162
#> # ... with 8 more rows
```

In the tidy alternative, `income` itself is a variable and the rows represent _observations_, which in this case are religion-income combinations.  

```r
pew %>%
  gather(income, frequency, -religion)
#> # A tibble: 180 x 3
#>    religion                income frequency
#>    <chr>                   <chr>      <int>
#>  1 Agnostic                <$10k         27
#>  2 Atheist                 <$10k         12
#>  3 Buddhist                <$10k         27
#>  4 Catholic                <$10k        418
#>  5 Don’t know/refused      <$10k         15
#>  6 Evangelical Prot        <$10k        575
#>  7 Hindu                   <$10k          1
#>  8 Historically Black Prot <$10k        228
#>  9 Jehovah's Witness       <$10k         20
#> 10 Jewish                  <$10k         19
#> # ... with 170 more rows
```

The US Census Bureau releases variables within tables, with variables often representing sub-categories within tables.  For example, household income categories can be acquired by state from Table B19001, which we'll get from the 1-year 2016 ACS.  When `output` is set to `wide`, our data resemble the messy example from the tidyr vignette: 

```r
hhinc <- get_acs(geography = "state", table = "B19001", 
                  year = 2016, survey = "acs1", output = "wide")

hhinc

# A tibble: 52 x 40
   B19001_001E B19001_001M B19001_002E B19001_002M B19001_003E B19001_003M B19001_004E B19001_004M
         <dbl>       <dbl>       <dbl>       <dbl>       <dbl>       <dbl>       <dbl>       <dbl>
 1     1852518       12189      176641        6328      120590        5347      117332        5956
 2      248468        2841        9066        1377        7301        1240        7545         932
 3     2519052       11479      184109        6989      123141        6489      116678        4765
 4     1142718        7341      101085        6031       75579        3958       71364        4519
 5    12944178       15703      699927       11559      584989       11873      526006        9875
 6     2108992        7767      108697        4740       80074        5196       81207        4568
 7     1357269        7141       70599        3625       49894        3580       49971        3798
 8      351085        3936       20673        2300       12893        1730       12843        1915
 9      281241        3152       30145        2839       14621        1941        9700        1694
10     7573456       23478      540162       12814      380118        9799      396960       10214
# ... with 42 more rows, and 32 more variables
```
 
In this example, each income category represents a subset of a broader `income` variable that in this instance is spread across the columns, like in the Pew data example from the vignette.  This does not represent tidy data, in my opinion.  In contrast, when `output` is set to `tidy`: 

```r
hhinc_tidy <- get_acs(geography = "state", table = "B19001", 
                      year = 2016, survey = "acs1", output = "tidy")

hhinc_tidy

# A tibble: 884 x 5
   GEOID    NAME   variable estimate   moe
   <chr>   <chr>      <chr>    <dbl> <dbl>
 1    01 Alabama B19001_001  1852518 12189
 2    01 Alabama B19001_002   176641  6328
 3    01 Alabama B19001_003   120590  5347
 4    01 Alabama B19001_004   117332  5956
 5    01 Alabama B19001_005   108912  5308
 6    01 Alabama B19001_006   102080  4740
 7    01 Alabama B19001_007   103366  5246
 8    01 Alabama B19001_008    91011  4699
 9    01 Alabama B19001_009    86996  4418
10    01 Alabama B19001_010    74864  4210
# ... with 874 more rows
```

Our data now resemble the "tidy" example from the vignette.  Each observation represents a state-income combination, with income category found in the `variable` column and data values found in the `estimate` and `moe` columns, respectively.  I do give the estimate and margin of error their own columns as I interpret the MOE as belonging to the estimate rather than as a variable in its own right.   

Part of the confusion here may have to do with nomenclature.  The Census Bureau distributes data as __variables__; however, these variables often represent data __values__ (e.g. income categories, racial/ethnic groups, commuting mode, etc.).

**Comment by pat-s** [comment]
Thanks for the extensive answer @walkerke! 

I agree with your opinion on tidy data and that `output = wide` is not tidy. What I came across and what was the reason for this question is the following:

```r
df = get_acs(variables = c("B16008_002", "B19013_001", "B07401_001",
                            "B13002_002"), geometry = TRUE,
             geography = "state", output = "tidy", cache = TRUE)
```
If one does not download tables but variables, multiple unrelated variables get stored in the same column. This quickly leads to missinterpretation of data. For example if one now plots `estimate` against `NAME`, everything is mixed up. 
Of course, if one downloads only a single table with variables belonging together than `output = "tidy"` works great.

If you agree with me, what about the following: 
* If a user downloads tables, `output ` is set to `"tidy"` to automatically gather all variables of these tables. 
* If a user downloads **multiple** variables, `output` is set to `"wide"` so that unrelated variables are not mixed. 
* If one DL variables and sets `output = "tidy"`, a warning is thrown that this might lead to falsely formatted data. 
* If one DL variables AND tables, warn about mixing both up (or do not allow it at all in one call?). 

I just read again the vignettes and this mixing problem is not addressed their as well as the difference between variables and tables. This is also the basic problem that got me into writing this issue in the first place. Please correct me if I'm wrong :smile:
