### ISSUE TITLE
Got some zero values for female percentage for some zip codes 

### ISSUE THREAD

**Issue by jiangyu1208** [walkerke/tidycensus#531]
I need to get the female percentage based on the zip code level but I got some zero values. I don't know how to modify my code.

```
library(tidycensus)
library(tidyverse)

# Create the data frame
zipcode_df <- data.frame(as.character(c(39309, 87040, 78712)))

# Rename the column to "zipcode"
colnames(zipcode_df)[1] <- "zipcode"

# Display the result
print(zipcode_df)

# Set up Census  key
census_api_key("94d96c1dfb04afe285d0db958f78ded8a4b197f7")

# Get total population and female population for all zip code tabulation areas (ZCTAs)
population_gender <- get_acs(
  geography = "zcta",
  variables = c("total_population" = "B01003_001E",
                "female_population" = "B01001A_017"),
  year = 2021,
  survey = "acs5",
  output = "wide"
) |>
  mutate(zipcode = as.character(GEOID)) |>
  select(zipcode, total_population, female_populationE) |>
  rename(female_population = female_populationE)

# Calculate the percentage of male population
percentage_female_population <- population_gender %>%
  mutate(percentage_female = (female_population / total_population) * 100) %>%
  select(zipcode, percentage_female)

outcome <- zipcode_df |> left_join(percentage_female_population, by = "zipcode")
``` 

```
> outcome
  zipcode percentage_female
1   39309                 0
2   87040                 0
3   78712                 0
```

**Comment by walkerke** [comment]
A couple things:

- You shouldn't be using B01001A_017; that's from the table for the White population, so you are leaving out all nonwhite residents.  This is why you get 0 for 87040.  Use B01001_026 instead.  
- The other two ZCTAs are unique; one is a Naval Air Station in Mississippi (which potentially is only capturing male barracks) and the other is the University of Texas's business address, which I believe most dormitories don't use.  

If you see results like this, I'd recommend investigating them in this way as they likely reflect underlying meaning in the data rather than an error in tidycensus.

**Comment by jiangyu1208** [comment]
Thanks for your help. Really appreciate it. I have another question to calculate the ethnicity percentage from the block group. Do I find the right variable? 
![Screenshot 2023-09-04 at 00 33 06](https://github.com/walkerke/tidycensus/assets/31513652/0d88b09a-775a-435b-9ee1-7dea7db2c286)
