### ISSUE TITLE
Bug with get_estimates and 2021 vintage data

### ISSUE THREAD

**Issue by nmmarquez** [walkerke/tidycensus#544]
Hey there. It looks like there is an issue with the `get_estimates` function for the years 2021 and 2020. The code looks like it is currently pulling form the latest vintage rather than the vintage for the specified year see https://github.com/walkerke/tidycensus/blob/master/R/estimates.R#L83-L96.

This looks to only be an issue for years 2020 and onward. The code snippet below shows how I came upon this issue.

```r
rm(list=ls())
library(tidyverse)
library(tidycensus)

# pull in vintage 2022 (v22) data using tidy census (tc)
tc_v22_df <- get_estimates(
    "state", "components", year = 2022, time_series = TRUE) %>%
    rename(tc_value = value)

# pull in vintage 2021 (v21) data using tidy census (tc)
tc_v21_df <- get_estimates(
    "state", "components", year = 2021, time_series = TRUE) %>%
    rename(tc_value = value)

# pull in vintage 2022 (v22) data directly from the flat file (ff)
ff_v22_df <- "https://www2.census.gov/programs-surveys/popest/datasets/" %>%
    str_c("2020-2022/state/totals/NST-EST2022-ALLDATA.csv") %>%
    read_csv() %>%
    select(-SUMLEV, -REGION, -DIVISION) %>%
    rename(GEOID = STATE) %>%
    pivot_longer(-(GEOID:NAME)) %>%
    mutate(variable = str_remove(name, "[0-9].*")) %>%
    mutate(year = as.integer(str_remove(name, variable))) %>%
    select(-name) %>%
    rename(ff_value = value)

# pull in vintage 2021 (v21) data directly from the flat file (ff)
ff_v21_df <- "https://www2.census.gov/programs-surveys/popest/datasets/" %>%
    str_c("2020-2021/state/totals/NST-EST2021-alldata.csv") %>%
    read_csv() %>%
    select(-SUMLEV, -REGION, -DIVISION) %>%
    rename(GEOID = STATE) %>%
    pivot_longer(-(GEOID:NAME)) %>%
    mutate(variable = str_remove(name, "[0-9].*")) %>%
    mutate(year = as.integer(str_remove(name, variable))) %>%
    select(-name) %>%
    rename(ff_value = value)

# tc v22 matches nicely with the ff v22
tc_v22_df %>%
    filter(variable == "DOMESTICMIG") %>%
    left_join(ff_v22_df) %>%
    filter(tc_value != ff_value)

# not the case for vintage 21 looks like it is still pulling from the
# most recent vintage
tc_v21_df %>%
    filter(variable == "DOMESTICMIG") %>%
    left_join(ff_v21_df) %>%
    filter(tc_value != ff_value)

# this behavior is not seen in years prior to 2020 where the cnesus api is used
tc_v19_df <- get_estimates(
    "state", "components", year = 2019, time_series = TRUE) %>%
    rename(v19_value = value)

tc_v15_df <- get_estimates(
    "state", "components", year = 2015, time_series = TRUE) %>%
    rename(v15_value = value) %>%
    select(-NAME)

tc_v19_df %>%
    filter(NAME == "Oregon", variable == "DOMESTICMIG") %>%
    left_join(tc_v15_df)
```

**Comment by walkerke** [comment]
Census always recommends pulling from the latest vintage available and grabbing data from that vintage using earlier years.  As I implemented the new functionality with the 2022 release being the most recent, I'm not likely to support the older datasets (as you can still get the data you need anyway).

**Comment by walkerke** [comment]
See here: https://www.census.gov/programs-surveys/popest/guidance.html

> Postcensal Estimates
Each year, PEP utilizes current data on births, deaths, and migration to calculate population change since the date of the most recent decennial census and produce time series of estimates of population, demographic components of change, and housing units. The annual time series of estimates begins with the date of the most recent decennial census data and extends to the vintage year.

As each vintage of estimates includes all years since the most recent decennial census, the latest vintage of data available supersedes all previously produced estimates for those dates. Therefore, in most cases, you should work with the newest vintage of data available. For example, if you are looking for an estimate for July 1, 2020, you should select that estimate from the newest vintage of data available, and not from Vintage 2020.

**Comment by nmmarquez** [comment]
That makes sense. My only concern is the confusion that `get_estimates(year=2017)` will pull census vintage 2017 estimates, which are not the most recent up to dates estimates for that year, while  `get_estimates(year=2021)` will pull census vintage 2022 estimates, which to date are the best estimates for that year. This seems to be inconsistent behavior across years and doesn't match the documentation for the parameter year.

"The data year (defaults to 2022). It is recommended to use the most recent vintage available for a given decennial series (so, year = 2019 for the 2010s, and year = 2022 for the 2020s) and use time_series = TRUE to access time-series estimates."

**Comment by walkerke** [comment]
@nmmarquez yeah, I understand that argument.  It's tricky because Census stopped supporting the PEP API, so I'm doing my best to "reproduce it" by parsing the flat files and returning data in a consistent way from previous years - though the data format isn't fully consistent.  

I'd have to put time in to parse the 2020 and 2021 vintage data to replicate that behavior, and I wasn't sure of the value-add there as it took me quite some time to get the 2022 vintage data in a usable format.  I'd be open to a pull request from the user community, however, if they want to take a crack at it.

**Comment by walkerke** [comment]
Reopening with the release of the 2023 estimates.  

I need to think about the best way to handle year vs. vintage with the new estimates.  In theory users should be able to request a year / vintage combination (which I didn't allow when the estimates were on the API) - e.g. if they wanted the 2021 estimates from the 2022 vintage (even though revised 2021 estimates from the 2023 vintage would be available).

**Comment by nmmarquez** [comment]
This work is greatly appreciated, you have made my workflows so much easier to manage. You are the 🐐.

**Comment by walkerke** [comment]
Thank you!  FYI - I've been using your smoothHP package, it's my favorite Hamilton-Perry implementation that I've come across.  Appreciate you sharing that!
