### ISSUE TITLE
geometry drops rows

### ISSUE THREAD

**Issue by RoyalTS** [walkerke/tidycensus#68]
I assume this is not expected behavior?

    > tidycensus::get_decennial(geograph = 'tract', variables = 'P0090001', year = 2010, geometry = FALSE, county = '005', state = '12') %>% nrow()
    [1] 44
    > tidycensus::get_decennial(geograph = 'tract', variables = 'P0090001', year = 2010, geometry = TRUE, county = '005', state = '12') %>% nrow()
    [1] 43

(the tract being dropped has zero total population (`P0090001`))

**Comment by walkerke** [comment]
It is expected behavior.  The tract in question in the example above is a water-only tract off the coast of Panama City, Florida.  The cartographic boundary shapefiles used by tidycensus are clipped to the shoreline of the US and thus omit water-only tracts that lie off the coast.  

That said - you _have_ indirectly encountered a bug.  You _should_ be able to use the regular TIGER/Line shapefiles, and keep those tracts, by setting `cb = FALSE`, like in tigris.  For example: 

```r
library(tidycensus)
library(mapview)

bay_county <- get_acs(geography = "tract", variables = "B01003_001", 
                      geometry = TRUE, cb = FALSE, state = "12", county = "005")

mapview(bay_county)
```

![image](https://user-images.githubusercontent.com/4872833/38845995-b0038018-41bf-11e8-8b4e-52e1c7d0f323.png)

However, this is throwing an error in `get_decennial()`, which I'll need to fix.

**Comment by RoyalTS** [comment]
Hmm, you'll know better what other people are going to expect when they pull such data. In as far as the data source for the geometry does not have anything for that tract I would have expected a left join and thus an `NA` for the geometry in the tidy data.frame. It seems weird to me that merely changing a boolean argument for whether I want a geometry or not changes the result set.

**Comment by RoyalTS** [comment]
Also: I think the behavior differs for `geography = 'block'`. I just pulled all blocks for the 2010 decennial and the number of blocks I got matches the total number of blocks, period, not just the non-water blocks.

**Comment by walkerke** [comment]
Hmm, that is worth thinking about, returning NA geometries for missing areas.  

There aren't cartographic boundary files for blocks - only TIGER/Line files - which is why you get that behavior.

**Comment by RoyalTS** [comment]
Given all that I think the `NA`s would at the very least produce results that are more transparent about these issues. I just stumbled on them because I did some fairly anal testing.

**Comment by walkerke** [comment]
You've convinced me; rows not in the cartographic boundary files now have empty geometries (https://www.r-spatial.org/r/2017/03/19/invalid.html#empty-geometries) as of https://github.com/walkerke/tidycensus/commit/944c1bce35f2993a6586301ad731656633f850a4.  I'll leave this issue open until I fix the other issue regarding `cb = FALSE` for `get_decennial()`.

**Comment by RoyalTS** [comment]
Always good to be convincing :)

Thanks for the quick turn-around!
