### ISSUE TITLE
Problem with county changes

### ISSUE THREAD

**Issue by emoro** [walkerke/tidycensus#79]
When running the following code 
`age <- get_acs(geography="block group",table="B01001",state="VA",geometry=F,output="wide")`

I get the following error (after a while)
`Getting data from the 2012-2016 5-year ACS
Using FIPS code '51' for state 'VA'
Success No Content Success: (204) No Content
Error in as.character(x) : 
  cannot coerce type 'closure' to vector of type 'character'`

I tracked down the error to the "Bedford city" county, which has disappeared as a county, was changed to town status and added to Bedford County. 

Although I can get the data county by county (excluding Bedfor City), is there any way to still query all the block groups in "VA"? I guess a possible solution is to amend the figs_codes dataset included in the package, right?

**Comment by walkerke** [comment]
I'll get this fixed.  Thanks for filing the issue!

**Comment by wikge** [comment]
Thanks, @walkerke. This is a fantastic package.

@emoro, thanks for the suggestion to amend the fips_codes dataset. I made a new function from get_acs and added this to the beginning [based on other county name changes](https://www.census.gov/geo/reference/county-changes.html).
```
fips_codes <- fips_codes %>% filter(!(county %in% c("Bedford city", "Wade Hampton Census Area")),
                                      !(county == "Shannon County" & state == "SD"))
```
Then I added it to the tidycensus environment: `environment(get_acs_wg) <- asNamespace('tidycensus')`

This allowed me to pull 2016 ACS five-year estimates for every state with no issues.

**Comment by ajjitn** [comment]
To add to this, there seem to be three counties that have had [changes ](https://www.census.gov/geo/reference/county-changes.html)that make the `get_acs` function return a `204` error. 

1) Bedford City, VA (51115)
2) Shannon County, SD (46113)
3) Wade Hampton Census Area (02270)

Shannon County has changed its name to Oglala Lakota County, Wade Hampton Census Area has changed its name to Kulsivak Census Area and Bedford City was added to Bedford county and these changes all happened between 2013 and 2015. So these three counties are entirely extraneous and could be safely ignored if pulling acs data from after 2015. But I don't think it would be a good idea to remove these counties from the fips_codes dataset entirely because people might need to pull acs data from pre 2013 when these counties existed.

**Comment by walkerke** [comment]
Good observation @ajjitn.  I'm planning to generate a modified fips_codes dataset that has year-specific codes when applicable.  A query will then check the query year and use the appropriate lookup.  

I'm planning to put some dev time into tidycensus this week and next; I'll hopefully resolve this soon.

**Comment by walkerke** [comment]
I'm now using tigris to get an appropriate vector of counties for a given ACS yearly request, which solves this problem.
