### ISSUE TITLE
"Geometry for school district (unified) is not yet supported.  Use the tigris package and join as normal instead."

### ISSUE THREAD

**Issue by ylleketep** [walkerke/tidycensus#82]

**Comment by walkerke** [comment]
Is this a feature request?

**Comment by walkerke** [comment]
Closing due to lack of response.  For others who encounter this issue: you can get unified school district geometry for a state with: 

```r
library(tigris)

geom <- school_districts(state = "YOUR STATE", class = "sf")
```

Then use sf/dplyr to join to tidycensus data.  Geometry support for less common geographies is a relatively low development priority of mine, though I would welcome a pull request for this.
